# Data Exploration 03

You're working on an exhibit for a local museum called "The Titanic Disaster". They've asked you to analyze the passenger manifests and see if you can find any interesting information for the exhibit.

The museum curator is particularly interested in why some people might have been more likely to survive than others.

## Part 1: Import Polars and load the data

Remember to import Pandas the conventional way. If you've forgotten how, you may want to review [Data Exploration 01](https://byui-cse.github.io/cse450-course/module-01/exploration-01.html).

The dataset for this exploration is stored at the following url:

[https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv)

There are lots of ways to load data into your workspace. The easiest way in this case is to [ask Polars to do it for you](https://docs.pola.rs/user-guide/getting-started/#reading-writing).

### Initial Data Analysis
Once you've loaded the data, it's a good idea to poke around a little bit to find out what you're dealing with.

Some questions you might ask include:

* What does the data look like?
* What kind of data is in each column?
* Do any of the columns have missing values?

In [ ]:
# Part 1: Enter your code below to import Pandas according to the
# conventional method. Then load the dataset into a Pandas dataframe.

# Write any code needed to explore the data by seeing what the first few
# rows look like. Then display a technical summary of the data to determine
# the data types of each column, and which columns have missing data.

In [1]:
import polars as pl
df = pl.read_csv("https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv")
df.describe()
df.glimpse()
df.null_count()
df

Rows: 891
Columns: 12
$ PassengerId <i64> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
$ Survived    <str> 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes'
$ Pclass      <i64> 3, 1, 3, 1, 3, 3, 1, 3, 3, 2
$ Name        <str> 'Braund, Mr. Owen Harris', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss. Laina', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Allen, Mr. William Henry', 'Moran, Mr. James', 'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard', 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'Nasser, Mrs. Nicholas (Adele Achem)'
$ Sex         <str> 'male', 'female', 'female', 'female', 'male', 'male', 'male', 'male', 'female', 'female'
$ Age         <f64> 22.0, 38.0, 26.0, 35.0, 35.0, null, 54.0, 2.0, 27.0, 14.0
$ SibSp       <i64> 1, 1, 0, 1, 0, 0, 0, 3, 0, 1
$ Parch       <i64> 0, 0, 0, 0, 0, 0, 0, 1, 2, 0
$ Ticket      <str> 'A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450', '330877', '17463', '349909', '347742', '237736'
$ Fare        <f64> 7.25, 71.2833, 7.925, 53.1, 8.05, 8.4583, 51.8625, 21.075, 11.1333, 30.0708
$ Cabin       <str> null, 'C85', null, 'C123', null, null, 'E46', null, null, null
$ Embarked    <str> 'S', 'C', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'C'

shape: (891, 12)
┌─────────────┬──────────┬────────┬──────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name             ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ str      ┆ i64    ┆ str              ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 1           ┆ No       ┆ 3      ┆ Braund, Mr. Owen ┆ … ┆ A/5 21171  ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris           ┆   ┆            ┆         ┆       ┆          │
│ 2           ┆ Yes      ┆ 1      ┆ Cumings, Mrs.    ┆ … ┆ PC 17599   ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley     ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (Fl…             ┆   ┆            ┆         ┆       ┆          │
│ 3           ┆ Yes      ┆ 3      ┆ Heikkinen, Miss. ┆ … ┆ STON/O2.   ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina            ┆   ┆ 3101282    ┆         ┆       ┆          │
│ 4           ┆ Yes      ┆ 1      ┆ Futrelle, Mrs.   ┆ … ┆ 113803     ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (… ┆   ┆            ┆         ┆       ┆          │
│ 5           ┆ No       ┆ 3      ┆ Allen, Mr.       ┆ … ┆ 373450     ┆ 8.05    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William Henry    ┆   ┆            ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 887         ┆ No       ┆ 2      ┆ Montvila, Rev.   ┆ … ┆ 211536     ┆ 13.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Juozas           ┆   ┆            ┆         ┆       ┆          │
│ 888         ┆ Yes      ┆ 1      ┆ Graham, Miss.    ┆ … ┆ 112053     ┆ 30.0    ┆ B42   ┆ S        │
│             ┆          ┆        ┆ Margaret Edith   ┆   ┆            ┆         ┆       ┆          │
│ 889         ┆ No       ┆ 3      ┆ Johnston, Miss.  ┆ … ┆ W./C. 6607 ┆ 23.45   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Catherine Hele…  ┆   ┆            ┆         ┆       ┆          │
│ 890         ┆ Yes      ┆ 1      ┆ Behr, Mr. Karl   ┆ … ┆ 111369     ┆ 30.0    ┆ C148  ┆ C        │
│             ┆          ┆        ┆ Howell           ┆   ┆            ┆         ┆       ┆          │
│ 891         ┆ No       ┆ 3      ┆ Dooley, Mr.      ┆ … ┆ 370376     ┆ 7.75    ┆ null  ┆ Q        │
│             ┆          ┆        ┆ Patrick          ┆   ┆            ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────┴───┴────────────┴─────────┴───────┴──────────┘

## Part 2: Initial Exploration

Using your visualization library of choice, let's first look at some features in isolation. Generate visualizations showing:

- A comparison of the total number of passengers who survived compared to those that died.
- A comparison of the total number of males compared to females
- A histogram showing the distribution of sibling/spouse counts
- A histogram showing the distribution of parent/child counts

In [5]:
# Add the lets-plot library
%pip install lets-plot
from lets_plot import *
LetsPlot.setup_html()

Collecting lets-plot
  Downloading lets_plot-4.11.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (9.7 kB)
Collecting pypng (from lets-plot)
  Downloading pypng-0.20220715.0-py3-none-any.whl.metadata (13 kB)
Collecting palettable (from lets-plot)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from lets-plot) (11.3.0)
Downloading lets_plot-4.11.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 14.5 MB/s eta 0:00:00
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 28.9 MB/s eta 0:00:00
Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 4.2 MB/s eta 0:00:00
Installing collected packages: pypng, palettable, lets-plot
Successfully installed lets-plot-4.11.0 palettable-3.3.3 pypng-0.20220715.0

In [18]:
# Part 2: # Write the code needed to generate the visualizations specified.
ggplot(df, aes(x='Survived')) + geom_bar() + labs(x='Survived', y='Count')

ggplot(df, aes(x='Sex')) + geom_bar() + labs(x='Sex', y='Count') + coord_flip()


ggplot(df, aes(x="SibSp")) + geom_histogram(binwidth=1)

In [32]:
(ggplot(df, aes(x="SibSp")) + geom_histogram() + scale_x_discrete(limits=list(range(0,9))) +
labs(x='SibSp', y='Count'))

## Part 3: Pairwise Comparisons
Use your visualization library of choice to look at how the survival distribution varied across different groups.

- Choose some features that you think might have had some influence over the likelihood of a titanic passenger surviving.

- For each of those features, generate a chart for each feature showing the survival distributions when taking that feature into account

In [32]:
# Write the code to explore how different features affect the survival distribution
ggplot(df, aes(x="Age")) + geom_histogram(binwidth=1)
ggplot(df, aes(x="Survived", fill="Sex")) + geom_histogram(binwidth=1)
ggplot(df, aes(x="Pclass", fill="Survived")) + \
    geom_bar() + \
    scale_x_continuous(breaks=[1, 2, 3]) + \
    facet_wrap("Sex") + \
    labs(x="Pclass", y="Count", fill="Survived")



ggplot(df, aes(x="Pclass", fill="Survived")) + \
    geom_bar() + \
    scale_x_continuous(breaks=[1, 2, 3]) + \
    facet_grid("Embarked", "Sex") + \
    labs(x="Pclass", y="Count", fill="Survived")

## Part 4: Feature Engineering

The museum curator wonders if the passenger's rank and title might have anything to do with whether or not they survived. Since this information is embedded in their name, we'll use "feature engineering" to create two new columns:

- Title: The passenger's title
- Rank: A boolean (true/false) indicating if a passenger was someone of rank.

For the first new column, you'll need to find a way to [extract the title portion of their name](https://pandas.pydata.org/docs/getting_started/intro_tutorials/10_text_data.html). Be sure to clean up any whitespace or extra punctuation.

For the second new column, you'll need to first look at a summary of your list of titles and decide what exactly constitutes a title of rank. Will you include military and eccelsiastical titles? Once you've made your decision, create the second column.

You may want to review prior Data Explorations for tips on creating new columns and checking for lists of values.

In [47]:
# Enter the code needed to create the two new columns


df = df.with_columns(
    pl.col("Name")
      .str.split(", ").list.get(1)
      .str.split(". ").list.get(0)
      .alias("Title")
)

df

df.group_by("Title").len().sort("len", descending=True)
df.select("Title").unique().sort("Title")
df.group_by("Title").len().sort("len", descending=True)

rank_titles = [
    "Capt", "Col", "Don", "Jonkheer",
    "Lady", "Major", "Rev", "Sir", "the Countess"
]

df = df.with_columns(
    pl.col("Title").is_in(rank_titles).alias("Rank")
)

df.select(["Title", "Rank"])

with pl.Config(tbl_rows=20):
    print(df.select("Title").unique().sort("Title"))

shape: (17, 1)
┌──────────────┐
│ Title        │
│ ---          │
│ str          │
╞══════════════╡
│ Capt         │
│ Col          │
│ Don          │
│ Dr           │
│ Jonkheer     │
│ Lady         │
│ Major        │
│ Master       │
│ Miss         │
│ Mlle         │
│ Mme          │
│ Mr           │
│ Mrs          │
│ Ms           │
│ Rev          │
│ Sir          │
│ the Countess │
└──────────────┘

### Revisit Visualizations
Now that you have the new columns in place. Revisit the pairwise comparison plots to see if the new columns reveal any interesting relationships.

In [49]:
# Enter the code needed to recheck the pairwise comparison.
ggplot(df, aes(x="Rank", fill="Survived")) + \
    geom_bar() + \
    labs(x="Rank", y="Count", fill="Survived")


ggplot(df, aes(x="Title", fill="Survived")) + \
    geom_bar() + \
    labs(x="Title", y="Count", fill="Survived")

## Part 5: Encoding

The museum has partnered with a data science group to build some interactive predicitive models using the titanic passenger data.

Many machine learning algorithms require categorical features to be **encoded** as numbers.

There are two approaches to this, label encoding (sometimes called factorization), and "one-hot" encoding.

### Label Encoding

Label encoding creates numeric labels for each categorical value. For example, imagine we have a feature in the data called `Pet` with these values for the first five rows: `['Dog', 'Cat', 'Dog', 'Dog', 'Bird']`.

We could create a new feature called `Pet_Encoded` where those values are represented as: `[0, 1, 0, 0, 2]`. Where `0 = Dog, 1 = Cat, and 2 = Bird`.

We first use `.cast(pl.Categorical)` to turn it into a categorical variable and then use [`.to_physical()`](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.to_physical.html) to convert it to the enumerated value

    myData = myData.with_columns(pl.col('Pet').cast(pl.Categorical).to_physical().alias('Pet_Encoded'))

In our machine learning algorithm could use the new `Pet_Encoded` feature in place of the `Pet` feature.

In [51]:
# Create a new column in the dataset called "Sex_Encoded" containing the
# label encoded values of the "Sex" column
df = df.with_columns(
    pl.col("Sex")
      .cast(pl.Categorical)
      .to_physical()
      .alias("Sex_Encoded")
)

df

shape: (891, 15)
┌─────────────┬──────────┬────────┬───────────────────┬───┬──────────┬───────┬───────┬─────────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Embarked ┆ Title ┆ Rank  ┆ Sex_Encoded │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---      ┆ ---   ┆ ---   ┆ ---         │
│ i64         ┆ str      ┆ i64    ┆ str               ┆   ┆ str      ┆ str   ┆ bool  ┆ u32         │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪══════════╪═══════╪═══════╪═════════════╡
│ 1           ┆ No       ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ S        ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ Harris            ┆   ┆          ┆       ┆       ┆             │
│ 2           ┆ Yes      ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ C        ┆ Mrs   ┆ false ┆ 1           │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆          ┆       ┆       ┆             │
│ 3           ┆ Yes      ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ S        ┆ Miss  ┆ false ┆ 1           │
│             ┆          ┆        ┆ Laina             ┆   ┆          ┆       ┆       ┆             │
│ 4           ┆ Yes      ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ S        ┆ Mrs   ┆ false ┆ 1           │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆          ┆       ┆       ┆             │
│ 5           ┆ No       ┆ 3      ┆ Allen, Mr.        ┆ … ┆ S        ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ William Henry     ┆   ┆          ┆       ┆       ┆             │
│ …           ┆ …        ┆ …      ┆ …                 ┆ … ┆ …        ┆ …     ┆ …     ┆ …           │
│ 887         ┆ No       ┆ 2      ┆ Montvila, Rev.    ┆ … ┆ S        ┆ Rev   ┆ true  ┆ 0           │
│             ┆          ┆        ┆ Juozas            ┆   ┆          ┆       ┆       ┆             │
│ 888         ┆ Yes      ┆ 1      ┆ Graham, Miss.     ┆ … ┆ S        ┆ Miss  ┆ false ┆ 1           │
│             ┆          ┆        ┆ Margaret Edith    ┆   ┆          ┆       ┆       ┆             │
│ 889         ┆ No       ┆ 3      ┆ Johnston, Miss.   ┆ … ┆ S        ┆ Miss  ┆ false ┆ 1           │
│             ┆          ┆        ┆ Catherine Hele…   ┆   ┆          ┆       ┆       ┆             │
│ 890         ┆ Yes      ┆ 1      ┆ Behr, Mr. Karl    ┆ … ┆ C        ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ Howell            ┆   ┆          ┆       ┆       ┆             │
│ 891         ┆ No       ┆ 3      ┆ Dooley, Mr.       ┆ … ┆ Q        ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ Patrick           ┆   ┆          ┆       ┆       ┆             │
└─────────────┴──────────┴────────┴───────────────────┴───┴──────────┴───────┴───────┴─────────────┘

### One-Hot Encoding

One problem with label encoding is that it can make a categorical variable appear as if it contains a quantitative relationship between its values.

In the example above, is Bird twice as important as Cat? Some algorithms might interpret those values that way.

One-Hot encoding avoids this problem by creating a new feature for each category. The value of the new feature is either `0` (is not this value) or `1` (is this value).

In pandas, we can use the [to_dummies()](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.to_dummies.html#) method to deal with this problem:

    myEncodedData = myData.to_dummies(columns=['Pet'])

In the case of our `Pet` example, the new features created by `get_dummies()` would be:

| Pet_is_Dog | Pet_is_Cat | Pet_is_Bird |
|:----------:|:----------:|:-----------:|
|      1     |      0     |      0      |
|      0     |      1     |      0      |
|      1     |      0     |      0      |
|      1     |      0     |      0      |
|      0     |      0     |      1      |

Notice that for our data, if `Pet_is_Bird` = 0 and `Pet_is_Cat` = 0, we know that the pet has to be a dog. So the `Pet_is_Dog` column contains redundant information. When this happens, we say that our data contains a _multicollinearity_ problem.

To avoid this, we can tell `to_dummies()` that we want to get rid of one of the columns using the `drop_first` parameter:

    myEncodedData = myData.to_dummies(columns=['Pet'], drop_first=True)

The main disadvantage to One-Hot encoding is that if the feature you're encoding has a lot of different values, it can result in a lot of extra features. This can sometimes lead to poor performance with some types of algorithms.

In [52]:
# Use the polars to_dummies() method to one-hot encode the Embarked column.
df = df.to_dummies(columns=["Embarked"])

## Part 6: Conclusions

Based on your analysis, what interesting relationships did you find? Write three interesting facts the museum can use in their exhibit.

## 🌟 Above and Beyond 🌟

1. There appears to be a lot of different variations of similar titles. (such as abbreviations for Miss and Mademoiselle).

   Scan through the different titles to see which titles can be consolidated, then use what you know about data manipulation to simplify the distribution.

   Once you've finished, check the visualizations again to see if that made any difference.

2. The museum curator has room for a couple of nice visualizations for the exhibit. Create additional visualizations that are suitable for public display.